#!/bin/sh

grep -q CentOS /etc/redhat-release && RPMKEYURL="https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7" \
                                   || RPMKEYURL="https://www.redhat.com/security/fd431d51.txt"

cat <<EOF >/etc/yum.repos.d/installmedia-dvd.repo
[installmedia-dvd]
name = Red Hat Local DVD Repository
baseurl =ftp://192.168.2.254/pub/dvd
enabled = 1
gpgkey = $RPMKEYURL
gpgcheck = 1
cost = 50
EOF
